CREATE TABLE product (
     id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name       VARCHAR(255) NOT NULL,
     price      INTEGER NOT NULL CHECK (price >= 0),
     image_url  VARCHAR(255)
);

CREATE TABLE member (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(30) NOT NULL,
    role     VARCHAR(50) NOT NULL
);
CREATE TABLE WISH_ITEMS (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    item_id    BIGINT NOT NULL,
    quantity   INT    NOT NULL CHECK (quantity >= 1),
    FOREIGN KEY (user_id) REFERENCES member(id),
    FOREIGN KEY (item_id) REFERENCES product(id)
);